Shop/Paymants/urls.py
from django.urls import path
from .views import payment_page , remove_from_cart_paymants , create_order

app_name = 'paymants'

urlpatterns = [
    path('', payment_page, name='payment_page'),
    path('remove_from_cart/<int:your_product_id>/', remove_from_cart_paymants, name='remove_from_cart'),
    path('create_order/', create_order, name='create_order'),
    ]

Shop/ShopApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render

def About_us(request):
    return render(request, 'main.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', About_us, name='About_us'),
    path('products/', include('Products.urls')),
    path('account/', include('Accounts.urls')),
    path('payment/', include('Paymants.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/Paymants/models.py
from django.db import models
from django.contrib.auth.models import User
from Products.models import Product

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, default='Pending')
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    shipping_address = models.CharField(max_length=255, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=[('Bank transfer', 'Bank transfer'), ('PayPal', 'PayPal')], default='Bank transfer')
    def __str__(self):
        return f"Order {self.id} by {self.user.username}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return f"{self.quantity} of {self.product.name} in Order {self.order.id}"

class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=[('Bank transfer', 'Bank transfer'), ('PayPal', 'PayPal')])
    status = models.CharField(max_length=20, default='Pending')

    def __str__(self):
        return f"Payment for Order {self.order.id} - {self.status}"

Shop/Paymants/views.py
from django.shortcuts import render, redirect
from .models import Order, OrderItem ,Payment
from Products.models import Product
from django.http import HttpResponse
from collections import Counter
from Accounts.views import accounts_page

def payment_page(request):
    if request.user.is_authenticated:
        cart = request.session.get('cart', [])
        if not cart:
            return redirect('products:product_list')
        cart_counter = Counter(cart)
        cart_items = []
        for product_id, quantity in cart_counter.items():
            product = Product.objects.get(id=product_id)
            cart_items.append({
                'product': product,
                'quantity': quantity 
            })
        print(f"Cart items: {cart_items}")
        total_amount = sum(item['product'].price * item['quantity'] for item in cart_items)
        return render(request,"Paymants/paymants.html", {'cart': cart_items,'total_amount': total_amount})
    else:
        return redirect(accounts_page)

def remove_from_cart_paymants(request, your_product_id):
    cart = request.session.get('cart', [])
    if your_product_id in cart:
        cart.remove(your_product_id)
        request.session['cart'] = cart
    return redirect('paymants:payment_page')

def create_order(request):
    if request.method == 'POST':
        shipping_address = request.POST.get('shipping_address')
        zip_code = request.POST.get('zipcode')
        payment_method = request.POST.get('paymant_method')
        cart = request.session.get('cart', [])
        cart_counter = Counter(cart)
        if not shipping_address or not zip_code or not payment_method:
            return redirect('paymants:payment_page')
        
        total_amount = sum(Product.objects.get(id=product_id).price * quantity for product_id, quantity in cart_counter.items())
        if total_amount <= 0:
            return HttpResponse("Your cart is empty or the total amount is zero. Please add items to your cart before proceeding to payment.")
        order = Order.objects.create(
            user=request.user,
            shipping_address=shipping_address,
            zip_code=zip_code,
            total_amount=total_amount,
            payment_method=payment_method,
            status='Pending',
        )
        Payment.objects.create(
            order=order,
            amount=order.total_amount,
            payment_method=payment_method,
            status='Pending',)
        
        for product_id, quantity in cart_counter.items():
            product = Product.objects.get(id=product_id)
            OrderItem.objects.create(
                order=order,
                product=product,
                quantity=quantity,
                price=product.price
            )
        
        
        request.session['cart'] = []
        del request.session['cart']
        return render(request, "Paymants/success.html", {'order': order , 'payment_method': payment_method})
    else:
        return redirect('paymants:payment_page')

Shop/Paymants/templates/Paymants/paymants.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Shopping Cart</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="form-container">
      <h1 class="cart-title">Your Shopping Cart</h1>
      {% if cart %}
        <div class="cart-list">
          {% for item in cart %}
            <div class="cart-item">
              <div class="cart-item-info">
                <h3>{{ item.product.name }}</h3>
                <p>Price: <span>${{ item.product.price }}</span></p>
                <p>Quantity: <span>{{ item.quantity }}</span></p>
              </div>
              <a class="remove-link" href="{% url 'paymants:remove_from_cart' item.product.id %}">✕</a>
            </div>
          {% endfor %}
        </div>
        <p class="total-amount">Total: <span>${{ total_amount }}</span></p>
        <form action="create_order/" method="post" class="paymants-form">
          {% csrf_token %}
          <div class="form-group">
            <label for="shipping_address">Shipping address:</label>
            <input type="text" name="shipping_address" id="shipping_address" required />
          </div>
          <div class="form-group">
            <label for="zipcode">Zip Code:</label>
            <input type="text" name="zipcode" id="zipcode"
              onkeypress="return (event.charCode >= 48 && event.charCode <= 57) && this.value.length < 5"
              required />
          </div>
          <div class="form-group">
            <label for="paymant_method">Payment Method:</label>
            <select name="paymant_method" id="paymant_method" required>
              <option value="PayPal">PayPal</option>
              <option value="Bank_transfer">Bank transfer</option>
            </select>
          </div>
          <button type="submit" class="submit-btn">Submit</button>
        </form>
      {% else %}
        <p class="empty-cart">Your cart is empty</p>
      {% endif %}
    </div>
    {% include "footer.html" %}
  </body>
</html>

Shop/Paymants/templates/Paymants/success.html
{% load static %}
{% include "navbar.html" %}
<title>Payment Success</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<div class="success-container">
  {% if payment_method == "PayPal" %}
    <h2 class="success-title">Thank you for your order!</h2>
    <p>Please send the payment to the following email address:</p>
    <div class="success-info"><b>example@gmail.com</b></div>
    <p>Make sure to include your order number in the payment comment.</p>
    <div class="order-id">Order ID: <span>{{ order.id }}</span></div>
  {% elif payment_method == "Bank_transfer" %}
    <h2 class="success-title">Thank you for your order!</h2>
    <p>Please transfer the amount to the following bank account:</p>
    <div class="success-info">2137 2137 2137 2137 2137 2137</div>
    <p>Make sure to include your order number in the payment information.</p>
    <div class="order-id">Order ID: <span>{{ order.id }}</span></div>
  {% endif %}
</div>
{% include "footer.html" %}